# Players need permission in order to trigger the features
use-permissions: false

# If a player is killed by a zombie, a new Zombie is spawned with the player's head
zombie-infecting: true

# If a player damages slimes/magma cubes with a shovel, they have a chance to drop slime balls/magma cream
slime-scooping: true
magmacube-scooping: true
slime-drop-chance: 50 # ranged from 1 to 100
extra-slime-count: 2