name: AdvancedCraft
version: '${project.version}'
main: me.trixxie.advancedcraft.AdvancedCraft
api-version: 1.19
authors: [ Trixxie ]
description: Advanced mechanics for your server
commands:
  advancedcraft:
    description: Get important information about plugin, and general commanding
    usage: /<command>
    aliases:
      - ac
      - advanced